name: Publish to GitHub Container Registry

on:
  # trigger manual workflow
  workflow_dispatch:
  # trigger workflow on push to master when changes happen in one folder
  push:
    branches:
      - main
  
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.5.0
        with:
          push: true
          tags: vincdelta/map-discordeventbot:v1.0.3